# Arctic Configuration
#
# copy this file to either:
# /etc/arctic/config.yml
# or
# ~/.arctic/config.yml

# the port artic server will run on and
# can be accessed from
server:
  port: 9726

# postgresdb source that arctic
# will connect to
postgres:
  host: localhost
  port: 5432
  user: arctic
  password: arctic
  name: arctic_db
  sslmode: disable # disable, require, verify-ca, verify-full

# log settings in arctic
log:
  level: info # debug, info, warn, error
  format: json # json, text

